#!/bin/sh
#PBS -N fineNum
#PBS -l nodes=1:ppn=4
#PBS -j oe

cd $PBS_O_WORKDIR

module load openfoam/2.4.0
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

runApplication blockMesh24
runApplication decomposePar

runApplication $application

runApplication reconstructPar
runApplication calcExtraVars
runApplication myWallHeatFlux
runApplication yPlus -compressible

# ----------------------------------------------------------------- end-of-file
