#!/bin/sh

cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

foamClearPolyMesh -region solid
foamClearPolyMesh -region fluid

rm -f *.OpenFOAM

rm -rf 0
