#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#create meshes
runApplication blockMesh24 -region fluid
mv log.blockMesh24 log.blockMesh24.fluid
runApplication blockMesh24 -region solid
mv log.blockMesh24 log.blockMesh24.solid

# create dummy files for post-processing
paraFoam -touch -region solid
paraFoam -touch -region fluid

cp -rf 0.org 0
# runApplication mapFields ../../coldFlow/kowf -targetRegion fluid -sourceTime latestTime
./setPressure

runApplication decomposePar -region fluid
mv log.decomposePar log.decomposePar.fluid
runApplication decomposePar -region solid
mv log.decomposePar log.decomposePar.solid

